# Generated by Django 3.0.2 on 2020-01-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(null=True),
        ),
    ]
